### ISSUE TITLE
`plotly` outputs not rendering

### ISSUE THREAD

**Issue by aadsouza** [QuantEcon/lecture-datascience.myst#142] opened 2021-06-07 17:03 UTC
see random forests output in `reg` lectures for example. https://quantecon.github.io/lecture-datascience.myst/applications/regression.html

**Comment by aadsouza** [comment] 2021-06-08 04:32
@mmcky this seems to have tripped without warning because we have `-W` turned on.

**Comment by mmcky** [comment] 2021-06-08 04:47
@aadsouza you talking about this section

https://quantecon.github.io/lecture-datascience.myst/applications/regression.html#regression-trees

**Comment by aadsouza** [comment] 2021-06-08 04:48
@mmcky yes

**Comment by mmcky** [comment] 2021-06-08 05:07
@AakashGfude any ideas why this `plotly` object isn't loading. 

It appears to be executing without issue

```
  {
   "cell_type": "code",
   "execution_count": 23,
   "id": "e78ba9a4",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "c1092fcab523498cab6acdf9d60b0b75",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "FigureWidget({\n",
       "    'data': [{'marker': {'opacity': 0.3, 'size': 2},\n",
       "              'mode': 'markers',\n",
       "         …"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
```

**Comment by aadsouza** [comment] 2021-06-08 05:17
note: would work as recently as the `pre-release` before this if i'm not mistaken

**Comment by mmcky** [comment] 2021-06-08 05:27
@AakashGfude it does look like the `html` has changed from `including` the script to `excluding` the script in the `html` output.

**Comment by aadsouza** [comment] 2021-06-11 01:09
was running the binder/colab test and noticed that this `plotly` stuff doesn't render anything there either

**Comment by mmcky** [comment] 2021-06-11 03:06
@AakashGfude the binder environment is now setup correctly and they render there ok.

**Comment by AakashGfude** [comment] 2021-06-11 06:09
Looks like it is an issue of mathjaxv3 and the plotly incompatibility . which had been raised earlier at https://github.com/plotly/plotly.js/issues/4563 .

In our case, `plotlywidgets` uses `MathJax.Hub.Config` which is Mathjaxv2 syntax.

On setting
```
mathjax_path: https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML
```

and then trying, the plot renders okay:
<img width="1261" alt="Screen Shot 2021-06-11 at 4 05 28 pm" src="https://user-images.githubusercontent.com/6542997/121639021-3fa8cc00-cacf-11eb-9d15-416ad6bb3d87.png">

But will keep trying out a solution to make it compatible with mathjaxv3.

**Comment by mmcky** [comment] 2021-06-11 10:28
@AakashGfude nice work!. That is a lot of layers to figure out. 

I guess we are going to have to wait for `plotly` to support `mathjax v3` (or we could revert to `mathjax v2` for datascience)

**Comment by mmcky** [comment] 2021-06-11 10:37
@AakashGfude one of the listed items on the `plotly` issue seems to have what `might` be a pretty straight forward temp fix.

https://github.com/project-lovelace/lovelace-website/pull/96/files

What do you think?

**Comment by AakashGfude** [comment] 2021-06-14 10:34
> @AakashGfude one of the listed items on the `plotly` issue seems to have what `might` be a pretty straight forward temp fix.
> 
> https://github.com/project-lovelace/lovelace-website/pull/96/files
> 
> What do you think?

I tried this particular fix from the repo. But did not seem to work. Maybe because our issue is in `plotlywidgets` file,  which has quite a lot of `mathjaxv2` specific syntax. 

One simple fix, as you mentioned is to revert to mathjaxv2 for datascience. 
And in the theme itself, we can read the config and change the syntax according to the version.

**Comment by wupeifan** [comment] 2021-06-14 17:39
Are the `plotlywidgets` needed when we are using Jupyter Lab, or they are also necessary when just running in plain notebooks?

**Comment by AakashGfude** [comment] 2021-06-15 12:26
> Are the `plotlywidgets` needed when we are using Jupyter Lab, or they are also necessary when just running in plain notebooks?

Seems like it. I think `Figurewidgets` use the `plotlywidget.js` file in the background? 
The particular code uses figurewidget for interactivity.

**Comment by AakashGfude** [comment] 2021-06-17 05:02
fixed in https://github.com/QuantEcon/lecture-datascience.myst/pull/156

**Closed by AakashGfude** 2021-06-17 05:02 UTC
Labels: high-priority
