### ISSUE TITLE
xgboost and other errors in heterogenous effects

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-datascience.myst#58] opened 2021-03-03 19:21 UTC
https://quantecon.github.io/lecture-datascience.myst/applications/heterogeneity.html

Probably needs `xgboost` or whatnot in the einvorment.

**Comment by aadsouza** [comment] 2021-03-11 05:49
found another: https://quantecon.github.io/lecture-datascience.myst/applications/regression.html
probably needs `graphviz` in the environment.

**Comment by aadsouza** [comment] 2021-04-06 01:49
issue is duplicate of #48

**Closed by aadsouza** 2021-04-06 01:49 UTC
